Jw added some functions
rapyuta-robotics/flatland pull request #10
Opened 2018-12-13 08:11 UTC by Vuwij

For the sonars

2018-12-13 11:10 UTC, gauthamm approved these changes

2018-12-13 11:10 UTC, hendrik-skubch requested changes

2018-12-13 11:10 UTC, hendrik-skubch commented on flatland_server/test/debug_visualization_test.cpp
> -  ASSERT_NEAR(markers.markers[0].points[0].x, -1.0, 1e-5);
Why are you removing these asserts?
Don't remove tests without providing at least equivalent tests

2018-12-14 02:41 UTC, hendrik-skubch approved these changes

2018-12-14 02:41 UTC, merged