Jw flipped lidar
rapyuta-robotics/flatland pull request #11
Opened 2019-01-25 11:28 UTC by Vuwij

Adds an option to flip the lidar

2019-01-25 12:34 UTC, hendrik-skubch reviewed
Err, why can this not be handled through the urdf?

2019-01-25 12:34 UTC, hendrik-skubch commented on flatland_plugins/src/laser.cpp
> +    if (!flipped_) {
Positive case first.

2019-01-25 12:34 UTC, hendrik-skubch commented on flatland_plugins/src/laser.cpp
> +      if (reflectance_layers_bits_) laser_scan_.intensities[i] = result.second;
braces

2019-01-27 12:57 UTC, gauthamm commented on flatland_server/src/debug_visualization.cpp
> +      case b2Shape::e_polygon: {  // Currently only
currently only?? what does that mean?

2019-01-27 12:57 UTC, gauthamm commented on flatland_plugins/src/laser.cpp
> +    if (!flipped_) {
```suggestion
    unsigned int index = (flipped_)? (laser_scan_.ranges.size() - i) : i;
    laser_scan_.ranges[index] = result.first + this->noise_gen_(this->rng_);	
    if (reflectance_layers_bits_) {
         laser_scan_.intensities[index] = result.second;
    }
```

2019-01-28 10:54 UTC, gauthamm requested changes

2019-01-28 10:54 UTC, gauthamm commented on flatland_plugins/src/laser.cpp
> +      laser_scan_.intensities[index] = result.second;
still missing braces

2019-01-29 01:24 UTC, hendrik-skubch commented on flatland_plugins/src/laser.cpp
> +    if (flipped_) {
having this check outside the loop is better imo. Now it is very hard for the compiler to understand that this is linear loop. You should be able to cast this as a use-case of std::transform.
Something along the lines of
`std::transform(results.begin(),results.end(),(_flipped? laser_scan_.ranges.rbegin() :  laser_scan_.ranges.begin(), [](const auto& res) { ... } );`

2019-01-29 13:56 UTC, gauthamm approved these changes

2019-01-30 03:32 UTC, merged